# Generated by Django 4.0.2 on 2022-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
