# Generated by Django 4.0.3 on 2022-06-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_coordenadas_lat_alter_coordenadas_lon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordenadas',
        ),
    ]
