# Generated by Django 4.0.3 on 2022-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_communitypost_display_communitypost_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='lat',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='community',
            name='lon',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
