# Generated by Django 4.0.3 on 2022-06-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_community_lat_alter_community_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='addr21',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
