# Generated by Django 4.0.3 on 2022-07-05 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunity_follower', to=settings.AUTH_USER_MODEL)),
                ('mycommunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycommunity', to='community.community')),
            ],
        ),
    ]
