# Generated by Django 4.0.2 on 2022-04-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='display',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.communitypost', verbose_name='親コメント'),
        ),
    ]
